### ISSUE TITLE
Lstm_attention.py

### ISSUE THREAD

**Issue by sanjayb678** [DeepsMoseli/Bidirectiona-LSTM-for-text-summarization-#3]
Line 66 In the encoder_decoder function throws an error, TypeError: list indices must be integers or slices, not tuple. 

Let me know if you need more details. Thanks.

**Comment by abdullahfde** [comment]
Hello, How we can fix this error ?

**Comment by PratikNalage** [comment]
I'm getting the following error:

```
Traceback (most recent call last):
  File "lstm_Attention.py", line 195, in <module>
    trained_model,encoder,decoder,history = encoder_decoder(train_data)
  File "lstm_Attention.py", line 101, in encoder_decoder
    decoder_outputs = decoder_dense(attention)
  File "/home/game-of-codes/anaconda3/envs/py3/lib/python3.6/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/game-of-codes/anaconda3/envs/py3/lib/python3.6/site-packages/keras/layers/core.py", line 866, in build
    constraint=self.kernel_constraint)
  File "/home/game-of-codes/anaconda3/envs/py3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/game-of-codes/anaconda3/envs/py3/lib/python3.6/site-packages/keras/engine/base_layer.py", line 249, in add_weight
    weight = K.variable(initializer(shape),
  File "/home/game-of-codes/anaconda3/envs/py3/lib/python3.6/site-packages/keras/initializers.py", line 209, in __call__
    scale /= max(1., float(fan_in + fan_out) / 2)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by xinmin323** [comment]
#  attention = Permute([2, 1])(attention)  # （？，300，？）
try to delete it ,but don't know why

**Comment by amanjaswani** [comment]
In the attention = Multiply()([decoder_outputs, attention]) line, I'm getting the following error "ValueError: Operands could not be broadcast together with shapes (None, 300) (151,)". I've searched a lot but don't know how to rectify this.
Please help me out :'(

**Comment by pp2805** [comment]
@amanjaswani Did you resolve that issue, because I'm too getting that error: "ValueError: Operands could not be broadcast together with shapes (None, 128) (300,)".

**Comment by Ramubala** [comment]
> In the attention = Multiply()([decoder_outputs, attention]) line, I'm getting the following error "ValueError: Operands could not be broadcast together with shapes (None, 300) (151,)". I've searched a lot but don't know how to rectify this.
> Please help me out :'(

you need to modify the function cutoffSequences
