### ISSUE TITLE
lstm_attention.py 

### ISSUE THREAD

**Issue by raghaviraman** [DeepsMoseli/Bidirectiona-LSTM-for-text-summarization-#7]
When I try to implement lstm_attentio.py I get an error as such,

Traceback (most recent call last):
  File "lstm_Attention.py", line 39, in <module>
    en_shape=np.shape(train_data["article"][0])
NameError: name 'train_data' is not defined

help me correct it

**Comment by MrinmoyDebnath** [comment]
train_data is the output from word2vec program

**Comment by MrinmoyDebnath** [comment]
> 
> 
> When I try to implement lstm_attentio.py I get an error as such,
> 
> Traceback (most recent call last):
> File "lstm_Attention.py", line 39, in
> en_shape=np.shape(train_data["article"][0])
> NameError: name 'train_data' is not defined
> 
> help me correct it

train_data is the output from word2vec program
